name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "iac/**"

jobs:
  create-roylarsenxyz-infrastrucutre:  
    name: Create roylarsen.xyz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main
      - uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.10
      - name: Terraform init
        run: terraform init
        working-directory: iac/roylarsen.xyz/
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply
        run: terraform apply --auto-approve
        working-directory: iac/roylarsen.xyz/
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          NAMECHEAP_USER_NAME: ${{ secrets.NAMECHEAP_USERNAME }} 
          NAMECHEAP_API_USER: ${{ secrets.NAMECHEAP_USERNAME }}
          NAMECHEAP_API_KEY: ${{ secrets.NAMECHEAP_API_KEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
