name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "iac/**"

jobs:
  create-roylarsenxyz-infrastrucutre:  
    name: Create roylarsen.xyz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.1.7
      - name: Terraform init - roylarsen.xyz
        run: terraform init
        working-directory: iac/roylarsen.xyz/
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply - roylarsen.xyz
        run: terraform apply --auto-approve
        working-directory: iac/roylarsen.xyz/
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform init - tastefuldinosaurerotica.com
        run: terraform init
        working-directory: iac/tastefuldinosaurerotica/
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Terraform Apply - tastefuldinosaurerotica.com
        run: terraform apply --auto-approve
        working-directory: iac/tastefuldinosaurerotica/
        env:
          DIGITALOCEAN_TOKEN: ${{ secrets.DIGITALOCEAN_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
