name: Deploy Infrastructure

on:
  push:
    branches:
      - main
    paths:
      - "iac/**"

jobs:
  run-terraform:
    name: Run Terraform
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_TOKEN }}
      - name: Test doctl
        run: doctl -h
      - name: Create Core Project
        run: doctl projects create --name CORE --purpose "DO Core Management"